### ISSUE TITLE
Windows version will not run because of error in generate.bat

### ISSUE THREAD

**Issue by danpolitte** [NASA-PDS/mi-label#10]
**Describe the bug**
The Windows version of `mi-label` version 1.1.2 does not work out-of-the-box. It is currently necessary for the user to manually edit line 52 of `mi-label-1.1.2\bin\generate.bat`, replacing the erroneous path in that line with `"%LIB_DIR%\mi-label-*.jar"`, before any call to `generate` will complete successfully.

**To Reproduce**
1. On a machine running Windows 10, follow the installation and configuration steps specified on [this page](https://nasa-pds.github.io/mi-label/install/index.html) to install the `mi-label` version 1.1.2. (I downloaded it from [https://github.com/NASA-PDS/mi-label/releases/download/v1.1.2/mi-label-1.1.2-bin.zip](https://github.com/NASA-PDS/mi-label/releases/download/v1.1.2/mi-label-1.1.2-bin.zip).) For the purposes of these steps, the installation directory is assumed to be `C:\pds\mi-label-1.1.2`.
1. Ensure that the user's path does not contain the bin directory of any previous install of `mi-label` or `generate`, so that the `generate` command will run the file `C:\pds\mi-label-1.1.2\bin\generate.bat`.
1. Open an instance of Powershell and run the command `generate -V`.
1. See the error `Cannot find Generate Tool jar file in C:\pds\MI-LAB~1.2\bin\..\lib`, after which the program halts without completing the request.

**Expected behavior**
The version of the `mi-label` package should be displayed.

**Version of Software Used**
gov.nasa.pds:mi-label
Version 1.1.2
Release Date: 2020-05-11 20:38:25

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.1.2

**Comment by jordanpadams** [comment]
@danpolitte i believe we fixed this issue. please checkout our latest dev version and let us know if you run into any other issues. as an additional note: we also renamed the CLI tool to `pds-generate.bat`. hopefully that doesn't cause any issues.

https://github.com/NASA-PDS/mi-label/releases/tag/1.2.0-SNAPSHOT

**Comment by danpolitte** [comment]
@jordanpadams Yep, this resolves it. Thanks!
