### ISSUE TITLE
.toLowerCase mi-label-1.2.1

### ISSUE THREAD

**Issue by agicquelb** [NASA-PDS/mi-label#23]
Hey Jordan,

In the vm file I use .toLowerCase(). For example
<type>$label.TARGET_TYPE.substring(0,1)$label.TARGET_TYPE.substring(1).toLowerCase()</type>

In the previous version it would modify for example COMET to Comet. 

In the new mi-label-1.2.1 it doesn't understand the .toLowerCase() command:
<type>$label.TARGET_TYPE.substring(0,1)$label.TARGET_TYPE.substring(1).toLowerCase()</type>

Adeline

**Comment by jordanpadams** [comment]
@agicquelb can you provide the file you were trying to convert? (You may need to add a .txt to get it to upload)

**Comment by agicquelb** [comment]
I attached the files
[ros_cam1_20150923t060217c.lbl.txt](https://github.com/NASA-PDS/mi-label/files/7557194/ros_cam1_20
[ros_cam1_20150923t060217c.xml.txt](https://github.com/NASA-PDS/mi-label/files/7557197/ros_cam1_20150923t060217c.xml.txt)
150923t060217c.lbl.txt)
Adeline

**Comment by agicquelb** [comment]
Jordan,

I uploaded the files.

Adeline

**Comment by jordanpadams** [comment]
@agicquelb apologies there. due to some necessary code fixes, the object is now an array, so the new way to do this is:
```
$label.TARGET_TYPE[0].substring(0,1)$label.TARGET_TYPE[0].substring(1).toLowerCase()
```

Also, an alternative to this would be to use the [Apache Velocity Display Tool](https://velocity.apache.org/tools/3.1/tools-summary.html#DisplayTool) and do something like this:
```
$display.capitalize($label.FRAME_ID[0].toLowerCase())
```

**Comment by sslavney** [comment]
Hey, this is a non-backwards-compatible change to mi-label! I just spent a couple of hours trying to track down a similar problem in a template that used to work, before I found this issue. This has the potential to break many label templates used by Mars 2020 data providers and others. It should at least be documented in release notes or something!

**Comment by jordanpadams** [comment]
@sslavney apologies there. we thought this was a backwards-compatible change when it was merged and released, but apparently our test suite was not large enough.

downgrading to any version <1.2 should still work.
